version: "3.3"
services:
  # Express TypeScript API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  # PostgreSQL service
  db:
    build:
      context: . 
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=express_user
      - POSTGRES_PASSWORD=express_password
      - POSTGRES_DB=express
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
